%% read .cin file generated by Quantel and EyeScan system to create visualization.

clear all;clc;close all;

% Example usage:
dataDir = 'C:\Users\axm1287\Downloads\3D-UBM\data';
dataName = fullfile(dataDir, '555-250418-134419.cin');
logFileName = fullfile(dataDir, '2018-04-25-132902.log');
outputType = 'nii';

% Call functions with appropriate arguments
data = readCinFile(dataName);
[volumeInfo.xSpacing, volumeInfo.ySpacing, volumeInfo.zSpacing] = readLogFile(logFileName);
dataVolume = processCinData(data, 2048, 384, 8, 1100);


if outputType == 'mp4'
    createVideo(dataName, dataVolume);
elseif outputType == 'nii'
    createNifti(dataName, dataVolume, volumeInfo);
elseif outputType == 'png'
    createPng(dataName, dataVolume);
end

